# Generated by Django 5.1.6 on 2025-03-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_name_user_username_user_otp_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
